- name: Checks for Existing Curator CronJob
  changed_when: False
  failed_when: False
  register: has_crt
  shell: "{{ kube_client }} --kubeconfig {{ admin_kubeconfig }} -n {{ logging_ns }} describe cj curator"
- block:
  - name: Generates Curator CronJob Configuration
    template:
      dest: /tmp/curator.yaml
      group: root
      mode: 0640
      owner: root
      src: curator.j2
  - name: Installs Curator
    args:
      chdir: /tmp
    shell: "{{ kube_client }} --kubeconfig {{ admin_kubeconfig }} apply -f curator.yaml"
  - name: Cleanups Curator Temporary Assets
    file:
      dest: /tmp/curator.yaml
      state: absent
  when:
  - has_crt is defined
  - (has_crt.rc | default(0)) != 0
