- name: Checks for Existing Fluentd DaemonSet
  changed_when: False
  failed_when: False
  register: has_fd
  shell: "{{ kube_client }} --kubeconfig {{ admin_kubeconfig }} -n {{ logging_ns }} describe ds fluentd"
- block:
  - name: Generates Fluentd DaemonSet Configuration
    template:
      dest: /tmp/fluentd.yaml
      group: root
      mode: 0640
      owner: root
      src: fluentd.j2
  - name: Installs Fluentd
    args:
      chdir: /tmp
    shell: "{{ kube_client }} --kubeconfig {{ admin_kubeconfig }} apply -f fluentd.yaml"
  - name: Cleanups Fluentd Temporary Assets
    file:
      dest: /tmp/fluentd.yaml
      state: absent
  when:
  - has_fd is defined
  - (has_fd.rc | default(0)) != 0
