---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-rbdplugin-snapclass
driver: rbd.csi.ceph.com
parameters:
  clusterID: eb53775c-ec88-484f-b5f5-b421b55079d7
  snapshotNamePrefix: k8s-rpi-snap-
  csi.storage.k8s.io/snapshotter-secret-name: ceph-secret-admin
  csi.storage.k8s.io/snapshotter-secret-namespace: rbd-provisioner
deletionPolicy: Delete
