---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "eb53775c-ec88-484f-b5f5-b421b55079d7",
        "monitors": [
          "10.42.253.110",
          "10.42.253.111",
          "10.42.253.112"
        ],
        "cephFS": {
          "subvolumeGroup": "k8srpicsi"
        }
      }
    ]
metadata:
  name: ceph-csi-config
  namespace: rbd-provisioner
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-admin
  namespace: rbd-provisioner
stringData:
  userID: admin
  userKey: AQAPPMleEGZAMBAAap9XPdIEAHJqInsdSh1/CA==
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-user
  namespace: rbd-provisioner
stringData:
  userID: kube
  userKey: AQAKfNJeC/z0FhAAbmBgMu0NdWUw2wfua4Lf9Q==
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: rwo-storage
allowVolumeExpansion: true
parameters:
  clusterID: eb53775c-ec88-484f-b5f5-b421b55079d7
  csi.storage.k8s.io/provisioner-secret-name: ceph-secret-admin
  csi.storage.k8s.io/provisioner-secret-namespace: rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-name: ceph-secret-admin
  csi.storage.k8s.io/controller-expand-secret-namespace: rbd-provisioner
  csi.storage.k8s.io/node-stage-secret-name: ceph-secret-user
  csi.storage.k8s.io/node-stage-secret-namespace: rbd-provisioner
  csi.storage.k8s.io/fstype: ext4
  imageFeatures: layering
  imageFormat: "2"
  mapOptions: nbds_max=16
  mounter: rbd-nbd
  pool: kube
  volumeNamePrefix: k8s-rpi-
provisioner: rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
