---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ceph-test
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
  containers:
  - name: dummy
    command: [ /bin/sh ]
    args:
    - -c
    - sleep 86400
    image: busybox
    volumeMounts:
    - name: mypvc
      mountPath: /data
  securityContext:
    runAsUser: 1001
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: test-pvc
