{
 "title": "Ansible Operator Overview",
 "description": "Ansible Operator overview.",
 "tags": [
  "ansible",
  "kubernetes",
  "operator"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ansible_operator_reconciles_bucket,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(ansible_operator_reconciles_bucket{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "crd",
    "label": "Resource Kind",
    "query": "label_values(ansible_operator_reconciles_bucket{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},GVK)"
   },
   {
    "name": "podname",
    "label": "Kubernetes Pod Name",
    "query": "label_values(ansible_operator_reconciles_bucket{kubernetes_cluster=~\"$cluster\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"$podname\",container=~\".+\"}[5m])",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"$podname\",container=~\".+\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Reconcile Results",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,GVK,result) (increase(ansible_operator_reconcile_result{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"}[6h]))",
     "legendFormat": "{{result}} {{GVK}} {{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Work Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,GVK,name) (workqueue_work_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"} / workqueue_work_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,GVK,name) (workqueue_queue_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"} / workqueue_queue_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{name}}"
    }
   ]
  },
  {
   "title": "Reconciles Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,GVK) (increase(ansible_operator_reconciles_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",GVK=~\"$crd\"}[6h]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{GVK}}"
    }
   ]
  }
 ]
}