{
 "title": "Apache",
 "description": "Apache metrics overview.",
 "tags": [
  "apache",
  "application"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(apache_server_uptime,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(apache_server_uptime{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "node",
    "label": "Kubernetes Host",
    "query": "label_values(apache_server_uptime{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_node_name)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(apache_server_uptime{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": "label_values(apache_server_uptime{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Min Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(apache_server_uptime{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_node_name=~\"$node\",kubernetes_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "graph",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(apache_version{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "Apache Up"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "rate(http_response_size_bytes_sum{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} bytes Sent"
    },
    {
     "expr": "rate(http_request_size_bytes_sum{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} bytes Received"
    }
   ]
  },
  {
   "title": "Current total apache accesses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apache_total_accesses{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Accesses"
    }
   ]
  },
  {
   "title": "Apache Requests per Second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_requests_per_second{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,worker) (apache_total_workers{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{worker}}"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_cpu_load{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Load"
    }
   ]
  }
 ]
}