{
 "title": "Cassandra",
 "description": "Cassandra metrics overview.",
 "tags": [
  "cassandra",
  "cluster",
  "database",
  "nosgbd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "kube",
    "label": "Kubernetes Cluster",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:max\"},kubernetes_cluster)"
   },
   {
    "name": "cluster",
    "label": "Cassandra Cluster",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:max\",kubernetes_cluster=~\"$kube\"},cluster)"
   },
   {
    "name": "datacenter",
    "label": "Cassandra Datacenter",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:max\",kubernetes_cluster=~\"$kube\"},datacenter)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:max\",kubernetes_cluster=~\"$kube\",cluster=~\"$cluster\",datacenter=~\"$datacenter\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:max\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "host",
    "label": "Pod Name",
    "query": "label_values(cassandra_stats{name=\"java:lang:memory:heapmemoryusage:max\",kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:net:failuredetector:upendpointcount\"})"
    }
   ]
  },
  {
   "title": "Nodes down",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:net:failuredetector:downendpointcount\"})"
    }
   ]
  },
  {
   "title": "Native clients connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:client:connectednativeclients:value\"})"
    }
   ]
  },
  {
   "title": "Repair ratio",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:table:percentrepaired:value\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 10, "x": 12, "y": 0 },
   "content": "<img src=\"https://images.techhive.com/images/article/2014/06/cassandra-logo-fxd-100310326-primary.idge.jpg\" width=\"170\" height=\"120\" />\n<span style=\"font-family:verdana,geneva,sans-serif;\"><span style=\"font-size:28px;\"><span style=\"color:#ffffff;\">&nbsp;&nbsp;Cassandra cluster monitoring</span></span></span>\n"
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 }, "content": "# Cluster operations" },
  {
   "title": "Cluster ops",
   "type": "graph",
   "description": "Total aggregated requests per second cluster-wise",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "max(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:(read|write|casread|caswrite|rangeslice|viewwrite):latency:oneminuterate\"})",
     "legendFormat": "All"
    },
    {
     "expr": "max(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:oneminuterate\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "max(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:oneminuterate\"})",
     "legendFormat": "Write"
    },
    {
     "expr": "max(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:casread:latency:oneminuterate\"})",
     "legendFormat": "CasRead"
    },
    {
     "expr": "max(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:caswrite:latency:oneminuterate\"})",
     "legendFormat": "CasWrite"
    },
    {
     "expr": "max(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:rangeslice:latency:oneminuterate\"})",
     "legendFormat": "RangeSlice"
    },
    {
     "expr": "max(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:viewwrite:latency:oneminuterate\"})",
     "legendFormat": "ViewWrite"
    }
   ]
  },
  {
   "title": "Operations per instance",
   "type": "graph",
   "description": "Requests served by each instance of the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:(read|write|casread|caswrite|rangeslice|viewwrite):latency:oneminuterate\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 }, "content": "# Reads and Writes" },
  {
   "title": "Read operations",
   "type": "graph",
   "description": "Read operations per instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:oneminuterate\"}+0.00000001)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Write operations",
   "type": "graph",
   "description": "Write operations per instance",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:oneminuterate\"}+0.00000001)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 }, "content": "# Latencies" },
  {
   "title": "Maximum read latency per instance",
   "type": "graph",
   "description": "Maximum read latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:max\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "75th percentile read latency per instance",
   "type": "graph",
   "description": "75th percentile read latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:75thpercentile\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "99th percentile read latency per instance",
   "type": "graph",
   "description": "99th percentile read latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:read:latency:99thpercentile\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Maximum write latency per instance",
   "type": "graph",
   "description": "Maximum write latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:max\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "75th percentile write latency per instance",
   "type": "graph",
   "description": "75th percentile write latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:75thpercentile\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "99th percentile write latency per instance",
   "type": "graph",
   "description": "99th percentile write latency per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:write:latency:99thpercentile\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 }, "content": "# Timeouts and Unavailables" },
  {
   "title": "Timeouts per instance rate",
   "type": "graph",
   "description": "Timeouts for read and write for each instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:.*:timeouts:oneminuterate\"}+0.00000001)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} All"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:read:timeouts:oneminuterate\"}+0.00000001)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Read"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:write:timeouts:oneminuterate\"}+0.00000001)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Write"
    }
   ]
  },
  {
   "title": "Unavailables per instance rate",
   "type": "graph",
   "description": "Unavailables operations per instance",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:.*:unavailables:oneminuterate\"}+0.00000001)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} All"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:write:unavailables:oneminuterate\"}+0.00000001)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Write"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:clientrequest:read:unavailables:oneminuterate\"}+0.00000001)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Read"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 53 }, "content": "# Errors" },
  {
   "title": "Exceptions per instance",
   "type": "graph",
   "description": "Exceptions for each instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:storage:exceptions:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total connection timeouts",
   "type": "graph",
   "description": "Total connection timeouts in the cluster",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:connection:totaltimeouts:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 64 }, "content": "# Thread pools" },
  {
   "title": "Active tasks",
   "type": "graph",
   "description": "Active tasks per thread type",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:antientropystage:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AntiEntropyStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:cachecleanupexecutor:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} CacheCleanupExecutor"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:compactionexecutor:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} CompactionExecutor"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:gossipstage:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} GossipStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:hintsdispatcher:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} HintsDispatcher"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:internalresponsestage:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} InternalResponseStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:memtableflushwriter:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MemTableFlushWriter"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:memtablepostflush:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MemTablePostFlush"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:memtablereclaimmemory:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MemTableReclaimMemory"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:migrationstage:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MigrationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:miscstage:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MiscStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:pendingrangecalculator:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} PendingRangeCalculator"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:perdiskmemtableflushwriter_0:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} PerDiskMemTableFlushWriter"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:sampler:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Sampler"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:secondaryindexmanagement:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} SecondaryIndexManagement"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:validationexecutor:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ValidationExecutor"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:countermutationstage:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} CounterMutationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:mutationstage:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MutationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:readrepairstage:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ReadRepairStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:requestresponsestage:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RequestResponseStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:viewmutationstage:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ViewMutationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:transport:native-transport-requests:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} NativeTransportRequest"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "graph",
   "description": "Pending tasks per thread type",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:antientropystage:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AntiEntropyStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:cachecleanupexecutor:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} CacheCleanupExecutor"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:compactionexecutor:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} CompactionExecutor"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:gossipstage:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} GossipStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:hintsdispatcher:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} HintsDispatcher"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:internalresponsestage:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} InternalResponseStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:memtableflushwriter:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MemTableFlushWriter"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:memtablepostflush:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MemTablePostFlush"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:memtablereclaimmemory:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MemTableReclaimMemory"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:migrationstage:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MigrationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:miscstage:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MiscStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:pendingrangecalculator:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} PendingRangeCalculator"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:perdiskmemtableflushwriter_0:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} PerDiskMemTableFlushWriter"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:sampler:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Sampler"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:secondaryindexmanagement:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} SecondaryIndexManagement"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:validationexecutor:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ValidationExecutor"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:countermutationstage:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} CounterMutationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:mutationstage:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MutationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:readrepairstage:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ReadRepairStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:requestresponsestage:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RequestResponseStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:viewmutationstage:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ViewMutationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:transport:native-transport-requests:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} NativeTransportRequest"
    }
   ]
  },
  {
   "title": "Blocked tasks",
   "type": "graph",
   "description": "Blocked tasks per thread type",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:antientropystage:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} AntiEntropyStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:cachecleanupexecutor:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} CacheCleanupExecutor"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:compactionexecutor:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} CompactionExecutor"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:gossipstage:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} GossipStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:hintsdispatcher:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} HintsDispatcher"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:internalresponsestage:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} InternalResponseStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:memtableflushwriter:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MemTableFlushWriter"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:memtablepostflush:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MemTablePostFlush"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:memtablereclaimmemory:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MemTableReclaimMemory"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:migrationstage:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MigrationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:miscstage:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MiscStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:pendingrangecalculator:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} PendingRangeCalculator"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:perdiskmemtableflushwriter_0:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} PerDiskMemTableFlushWriter"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:sampler:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Sampler"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:secondaryindexmanagement:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} SecondaryIndexManagement"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:validationexecutor:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ValidationExecutor"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:countermutationstage:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} CounterMutationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:mutationstage:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} MutationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:readrepairstage:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ReadRepairStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:requestresponsestage:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RequestResponseStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:request:viewmutationstage:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ViewMutationStage"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:transport:native-transport-requests:currentlyblockedtasks:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} NativeTransportRequest"
    }
   ]
  },
  {
   "title": "Dropped messages rates",
   "type": "graph",
   "description": "Dropped messages rates by message type",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:batch_remove:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} BatchRemove"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:batch_store:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} BatchStore"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:counter_mutation:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} CounterMutation"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:hint:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Hint"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:mutation:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Mutation"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:paged_range:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} PagedRange"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:range_slice:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RangeSlice"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:read:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Read"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:read_repair:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} ReadRepair"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:request_response:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} RequestResponse"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=\"$cluster\",datacenter=~\"$datacenter\",name=\"org:apache:cassandra:metrics:droppedmessage:_trace:dropped:oneminuterate\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} _Trace"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 }, "content": "# Compactions and SSTables" },
  {
   "title": "Pending and Running compactions",
   "type": "graph",
   "description": "Pending and Running compactions per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:compaction:pendingtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Pending"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:threadpools:internal:compactionexecutor:activetasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Running"
    }
   ]
  },
  {
   "title": "Completed compactions",
   "type": "graph",
   "description": "Completed compactions per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:compaction:completedtasks:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total completed compactions",
   "type": "graph",
   "description": "Total completed compactions per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:compaction:totalcompactionscompleted:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Bytes compacted",
   "type": "graph",
   "description": "Bytes compacted per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:compaction:bytescompacted:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Live SSTables per instance",
   "type": "graph",
   "description": "Live SSTables per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:table:livesstablecount:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "SSTables per read histogram",
   "type": "graph",
   "description": "SSTables per read histogram percentiles",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:table:sstablesperreadhistogram:50thpercentile\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} 50th percentile"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:table:sstablesperreadhistogram:75thpercentile\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} 75th percentile"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:table:sstablesperreadhistogram:99thpercentile\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} 99th percentile"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:table:sstablesperreadhistogram:max\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} max"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 106 }, "content": "# Cache" },
  {
   "title": "KeyCache one minute hit rate per instance",
   "type": "graph",
   "description": "KeyCache one minute hit rate per instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:cache:keycache:oneminutehitrate:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "KeyCache size / entries per instance",
   "type": "graph",
   "description": "KeyCache size / entries per instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 108 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:cache:keycache:size:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Size"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:cache:keycache:entries:value\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Entries"
    }
   ]
  },
  {
   "title": "KeyCache hits / requests per instance",
   "type": "graph",
   "description": "KeyCache hits / requests per instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 108 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:cache:keycache:hits:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Hits"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:cache:keycache:requests:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Requests"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 115 }, "content": "# Storage and health" },
  {
   "title": "Load per instance",
   "type": "graph",
   "description": "Load per instance in bytes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (cassandra_stats{kubernetes_cluster=~\"$kube\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",cluster=~\"$cluster\",datacenter=~\"$datacenter\",name=~\"org:apache:cassandra:metrics:storage:load:count\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}