{
 "title": "Ceph Cluster",
 "description": "Ceph Cluster overview.",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ceph_health_status,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(ceph_health_status{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "instance",
    "label": "Exporter Instance",
    "query": "label_values(ceph_health_status{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_health_status{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_osd_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "In",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osds_in{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "In",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Out",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_in{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"} == bool 0)",
     "legendFormat": "Out",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_osd_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_osd_stat_bytes_used{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})/sum(ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "PG States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (ceph_pg_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (ceph_pg_active{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "sum (ceph_pg_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"} - ceph_pg_active{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Inactive"
    },
    {
     "expr": "sum (ceph_pg_undersized{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Undersized"
    },
    {
     "expr": "sum (ceph_pg_degraded{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Degraded"
    },
    {
     "expr": "sum (ceph_pg_inconsistent{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "sum (ceph_pg_down{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "OSD Latencies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile(0.95, ceph_osd_apply_latency_ms{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Apply Latency P_95"
    },
    {
     "expr": "quantile(0.95, ceph_osd_commit_latency_ms{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Commit Latency P_95"
    },
    {
     "expr": "avg(ceph_osd_apply_latency_ms{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Avg Apply Latency"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Avg Commit Latency"
    }
   ]
  },
  {
   "title": "Client connections in $interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Clients",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "increase(ceph_mds_server_handle_client_session{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "Clients",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "In Quorum",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(ceph_mon_quorum_status{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "IN",
     "units": "none",
     "valueHandler": "Text Only"
    },
    {
     "aggregation": "Last",
     "alias": "Total",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(ceph_mon_quorum_status{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "Total",
     "units": "none",
     "valueHandler": "Text Only",
     "warn": 2
    },
    {
     "aggregation": "Last",
     "alias": "MONs out of Quorum",
     "crit": 1.6,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "Never",
     "expr": "count(ceph_mon_quorum_status{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"}) - sum(ceph_mon_quorum_status{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"})",
     "legendFormat": "OUT",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1.1
    }
   ]
  },
  {
   "title": "Cluster I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Writes"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Pools Objects In/Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": " Egress (-) / Ingress (+)" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(ceph_pool_stored{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "OSD Capacity Utilization",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"} / ceph_osd_stat_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "Util (%)"
    }
   ]
  },
  {
   "title": "PGs per OSD",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "ceph_osd_numpg{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"}",
     "legendFormat": "#PGs"
    }
   ]
  },
  {
   "title": "Recovery Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops", "label": "Recovery Ops/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Op/s"
    }
   ]
  }
 ]
}