{
 "title": "Ceph RGW Details",
 "description": "Ceph RadosGW details.",
 "tags": [
  "ceph",
  "cluster",
  "rgw"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ceph_rgw_req,kubernetes_cluster)"
   },
   {
    "name": "rgw_servers",
    "label": "RadosGW Client",
    "query": "label_values(ceph_rgw_req{kubernetes_cluster=~\"$cluster\"},ceph_daemon)"
   },
   {
    "name": "interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "$rgw_servers GET/PUT Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (rate(ceph_rgw_get_initial_lat_sum{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"($rgw_servers)\"}[$interval]) / rate(ceph_rgw_get_initial_lat_count{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"($rgw_servers)\"}[$interval]))",
     "legendFormat": "{{ceph_daemon}} GET"
    },
    {
     "expr": "sum by (ceph_daemon) (rate(ceph_rgw_put_initial_lat_sum{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"($rgw_servers)\"}[$interval]) / rate(ceph_rgw_put_initial_lat_count{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"($rgw_servers)\"}[$interval]))",
     "legendFormat": "{{ceph_daemon}} PUT"
    }
   ]
  },
  {
   "title": "Workload Breakdown",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(ceph_rgw_failed_req{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]))",
     "legendFormat": "Failures"
    },
    {
     "expr": "sum (rate(ceph_rgw_get{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]))",
     "legendFormat": "GETs"
    },
    {
     "expr": "sum (rate(ceph_rgw_put{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]))",
     "legendFormat": "PUTs"
    },
    {
     "expr": "sum (rate(ceph_rgw_req{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]) - (rate(ceph_rgw_get{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]) + rate(ceph_rgw_put{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval])))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Bandwidth by HTTP Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (rate(ceph_rgw_get_b{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]))",
     "legendFormat": "{{ceph_daemon}} GETs"
    },
    {
     "expr": "sum by (ceph_daemon) (rate(ceph_rgw_put_b{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]))",
     "legendFormat": "{{ceph_daemon}} PUTs"
    }
   ]
  },
  {
   "title": "HTTP Request Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ceph_daemon) (rate(ceph_rgw_failed_req{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]))",
     "legendFormat": "{{ceph_daemon}} Requests Failed"
    },
    {
     "expr": "sum by (ceph_daemon) (rate(ceph_rgw_get{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]))",
     "legendFormat": "{{ceph_daemon}} GETs"
    },
    {
     "expr": "sum by (ceph_daemon) (rate(ceph_rgw_put{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]))",
     "legendFormat": "{{ceph_daemon}} PUTs"
    },
    {
     "expr": "sum by (ceph_daemon) (rate(ceph_rgw_req{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]) - (rate(ceph_rgw_get{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval]) + rate(ceph_rgw_put{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"[[rgw_servers]]\"}[$interval])))",
     "legendFormat": "{{ceph_daemon}} Other"
    }
   ]
  }
 ]
}