{
 "title": "Ceph RGW",
 "description": "Ceph RadosGW overview.",
 "tags": [
  "ceph",
  "cluster",
  "rgw"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ceph_rgw_req,kubernetes_cluster)"
   },
   {
    "name": "rgw_servers",
    "label": "Rados Gateway",
    "query": "label_values(ceph_rgw_req{kubernetes_cluster=~\"$cluster\"},ceph_daemon)"
   },
   {
    "name": "interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ceph_rgw_get_initial_lat_sum{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]) / rate(ceph_rgw_get_initial_lat_count{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "avg(rate(ceph_rgw_put_initial_lat_sum{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]) / rate(ceph_rgw_put_initial_lat_count{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]))",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "title": "Requests/$interval by RGW client",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (rgw_host) (label_replace(rate(ceph_rgw_req{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]), \"rgw_host\", \"$1\", \"ceph_daemon\", \"rgw.(.*)\"))",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "GET Latencies by RGW client",
   "type": "graph",
   "description": "Latencies are shown stacked, without a yaxis to provide a visual indication of GET latency imbalance across RGW hosts",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum by (rgw_host) (label_replace(rate(ceph_rgw_get_initial_lat_sum{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]),\"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\") / \nlabel_replace(rate(ceph_rgw_get_initial_lat_count{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]),\"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\"))",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "Bandwidth Consumed",
   "type": "graph",
   "description": "Total bytes transferred in/out of all radosgw instances within the cluster",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_rgw_get_b{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]))",
     "legendFormat": "GETs"
    },
    {
     "expr": "sum(rate(ceph_rgw_put_b{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]))",
     "legendFormat": "PUTs"
    }
   ]
  },
  {
   "title": "Bandwidth by RGW Instance",
   "type": "graph",
   "description": "Total bytes transferred in/out through get/put operations, by radosgw instance",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (rgw_host) ((label_replace(rate(ceph_rgw_get_b{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]), \"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\")) + (label_replace(rate(ceph_rgw_put_b{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]), \"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\")))",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  },
  {
   "title": "PUT Latencies by RGW Instance",
   "type": "graph",
   "description": "Latencies are shown stacked, without a yaxis to provide a visual indication of PUT latency imbalance across RGW hosts",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "sum by (rgw_host) (label_replace(rate(ceph_rgw_put_initial_lat_sum{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]),\"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\") / \nlabel_replace(rate(ceph_rgw_put_initial_lat_count{kubernetes_cluster=~\"$cluster\",ceph_daemon=~\"$rgw_servers\"}[$interval]),\"rgw_host\",\"$1\",\"ceph_daemon\",\"rgw.(.*)\"))",
     "legendFormat": "{{rgw_host}}"
    }
   ]
  }
 ]
}