{
 "title": "Ceph Pool Details",
 "description": "Ceph Pools details.",
 "tags": [
  "ceph",
  "cluster",
  "pool"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ceph_pool_metadata,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(ceph_pool_metadata{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "pool_name",
    "label": "Pool Name",
    "query": "label_values(ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ceph_pool_stored_raw{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Time till full",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(sum by (kubernetes_cluster,kubernetes_namespace,name) (((ceph_pool_max_avail{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"} - ceph_pool_stored{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}) / deriv(ceph_pool_stored{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[6h])) * on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",name=~\"$pool_name\"} > 0))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$pool_name Object In-/Egress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Objects out(-) / in(+) " }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,name) (deriv(ceph_pool_objects{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) * on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",name=~\"$pool_name\"})",
     "legendFormat": "{{name}} Objects per second"
    }
   ]
  },
  {
   "title": "Max Available by Pool",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,name) (ceph_pool_max_avail{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"} * on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",name=~\"$pool_name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$pool_name Client IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "iops", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,name) (irate(ceph_pool_rd{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) * on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",name=~\"$pool_name\"})",
     "legendFormat": "{{name}} Reads"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,name) (irate(ceph_pool_wr{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) * on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",name=~\"$pool_name\"})",
     "legendFormat": "{{name}} Writes"
    }
   ]
  },
  {
   "title": "$pool_name Client Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,name) (irate(ceph_pool_rd_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",name=~\"$pool_name\"})",
     "legendFormat": "{{name}} reads"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,name) (irate(ceph_pool_wr_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",name=~\"$pool_name\"})",
     "legendFormat": "{{name}} writes"
    }
   ]
  },
  {
   "title": "$pool_name Objects Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Objects" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,name) (increase(ceph_pool_objects{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) * on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",name=~\"$pool_name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$pool_name Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Objects" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,name) (ceph_pool_objects{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"} * on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",name=~\"$pool_name\"})",
     "legendFormat": "{{name}} Objects Count"
    }
   ]
  }
 ]
}