{
 "title": "Ceph Pool",
 "description": "Ceph Pools overview.",
 "tags": [
  "ceph",
  "cluster",
  "pool"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(ceph_pool_stored_raw,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(ceph_pool_stored_raw{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   { "name": "topk", "label": "Top K", "query": "5" }
  ]
 },
 "panels": [
  {
   "title": "Top $topk Client IOPS by Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,name) (topk($topk,rate(ceph_pool_rd{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}))",
     "legendFormat": "{{name}} - read"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,name) (topk($topk,rate(ceph_pool_wr{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}))",
     "legendFormat": "{{name}} - write"
    }
   ]
  },
  {
   "title": "Top $topk Client Throughput by Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Writes (+)" }
   ],
   "targets": [
    {
     "expr": "topk($topk,sum by (name) (rate(ceph_pool_rd_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}))",
     "legendFormat": "{{name}} read"
    },
    {
     "expr": "topk($topk,sum by (name) (rate(ceph_pool_wr_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) + on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}))",
     "legendFormat": "{{name}} write"
    }
   ]
  },
  {
   "title": "Top $topk Pools by Client IOPS",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk($topk,((irate(ceph_pool_rd{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) + irate(ceph_pool_wr{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m])) + on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Top $topk Pools by Throughput",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "topk($topk,(irate(ceph_pool_rd_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m]) + irate(ceph_pool_wr_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}[1m])) + on(pool_id) group_left(instance,name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}) "
    }
   ]
  },
  {
   "title": "Top $topk Pools By Capacity Used",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk($topk,((ceph_pool_stored{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"} / (ceph_pool_stored{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"} + ceph_pool_max_avail{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"})) * on(pool_id) group_left(name) ceph_pool_metadata{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"}))"
    }
   ]
  }
 ]
}