{
 "title": "Gitea",
 "description": "Gitea metrics overview.",
 "tags": [
  "application",
  "Gitea",
  "Go"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(gitea_repositories,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(gitea_repositories{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(gitea_repositories{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "podname",
    "label": "Kubernetes Pod",
    "query": "label_values(gitea_repositories{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Gitea HTTP Accesses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{code}}"
    }
   ]
  },
  {
   "title": "Gitea Repository & Mirrors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitea_mirrors{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Mirrors"
    },
    {
     "expr": "gitea_repositories{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Repositories"
    }
   ]
  },
  {
   "title": "Gitea Auth Sources",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitea_loginsources{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Login Sources"
    },
    {
     "expr": "gitea_oauths{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} OAuth"
    }
   ]
  },
  {
   "title": "Gitea Releases",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitea_releases{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Gitea Organizations & Teams",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitea_organizations{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Organizations"
    },
    {
     "expr": "gitea_teams{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Teams"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[5m])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Gitea Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitea_actions{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Gitea Issues, Labels & Milestones",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitea_issues{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Issues"
    },
    {
     "expr": "gitea_labels{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Labels"
    },
    {
     "expr": "gitea_milestones{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Milestones"
    }
   ]
  },
  {
   "title": "Gitea Users & Public Keys",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitea_users{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Users"
    },
    {
     "expr": "gitea_publickeys{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Public Keys"
    }
   ]
  },
  {
   "title": "Go Threads & File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Threads"
    },
    {
     "expr": "process_open_fds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} FileDescriptors"
    }
   ]
  },
  {
   "title": "Gitea Hooks & Tasks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitea_webhooks{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Webhooks"
    },
    {
     "expr": "gitea_updatetasks{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Update Tasks"
    },
    {
     "expr": "gitea_watches{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Watches"
    },
    {
     "expr": "gitea_hooktasks{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Hook Tasks"
    }
   ]
  },
  {
   "title": "Gitea Comments & Attachments",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitea_comments{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Comments"
    },
    {
     "expr": "gitea_attachments{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Attachments"
    }
   ]
  },
  {
   "title": "Gitea Vanity Metrics",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitea_stars{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Stars"
    },
    {
     "expr": "gitea_follows{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Follows"
    }
   ]
  }
 ]
}