{
 "title": "Go Applications",
 "description": "Go Applications overview.",
 "tags": [
  "application",
  "Go"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(go_memstats_alloc_bytes,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(go_memstats_alloc_bytes{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(go_memstats_alloc_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "nodename",
    "label": "Kubernetes Host",
    "query": "label_values(go_memstats_alloc_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_node_name)"
   },
   {
    "name": "podname",
    "label": "Pod Name",
    "query": "label_values(go_memstats_alloc_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$nodename\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,kubernetes_pod_name) (process_resident_memory_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} resident"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,kubernetes_pod_name) (process_virtual_memory_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,kubernetes_pod_name) (go_memstats_alloc_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} alloc rate"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,kubernetes_pod_name) (go_memstats_stack_inuse_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} stack inuse"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,kubernetes_pod_name) (go_memstats_heap_inuse_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,kubernetes_pod_name) (process_open_fds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,kubernetes_pod_name) (go_goroutines{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,kubernetes_pod_name,quantile) (go_gc_duration_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{quantile}}"
    }
   ]
  }
 ]
}