{
 "title": "Kubernetes Nodes",
 "description": "Kubernetes Nodes overview.",
 "tags": [
  "cluster",
  "kubernetes"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(kubernetes_cluster)"
   },
   {
    "name": "node",
    "label": "Kubernetes Host",
    "query": "label_values(kubernetes_node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Idle cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\",kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}[5m])) * 100)",
     "legendFormat": "core #{{cpu}}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}} load 1m"
    },
    {
     "expr": "node_load5{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}} load 5m"
    },
    {
     "expr": "node_load15{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}} load 15m"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"} - node_memory_MemFree_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"} - node_memory_Buffers_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"} - node_memory_Cached_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}} memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}} memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}} memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}} memory free"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((node_memory_MemTotal_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"} - node_memory_MemFree_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}  - node_memory_Buffers_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"} - node_memory_Cached_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}) / node_memory_MemTotal_bytes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}) * 100)"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_node_name) (rate(node_disk_read_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}[2m]))",
     "legendFormat": "{{kubernetes_node_name}} read"
    },
    {
     "expr": "sum by (kubernetes_node_name) (rate(node_disk_written_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}[2m]))",
     "legendFormat": "{{kubernetes_node_name}} written"
    },
    {
     "expr": "sum by (kubernetes_node_name) ((rate(node_disk_io_time_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}[2m])) * 1000)",
     "legendFormat": "{{kubernetes_node_name}} io time (ms)"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",device!~\"lo\"}[5m])",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}} {{device}}"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",device!~\"lo\"}[5m])",
     "legendFormat": "{{kubernetes_cluster}}/{{kubernetes_node_name}} {{device}}"
    }
   ]
  }
 ]
}