{
 "title": "MySQL Wait Event Analyses",
 "description": "MySQL Wait Event Analyses metrics overview.",
 "tags": [
  "database",
  "mysql",
  "sgbd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(mysql_global_variables_performance_schema,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(mysql_global_variables_performance_schema{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(mysql_global_variables_performance_schema{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "host",
    "label": "Pod Name",
    "query": "label_values(mysql_global_variables_performance_schema{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\"},kubernetes_pod_name)"
   },
   {
    "name": "event",
    "label": "Event",
    "query": "label_values(mysql_perf_schema_events_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\"},event_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h3><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$host</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h3>"
  },
  {
   "title": "Count - Performance Schema Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (rate(mysql_perf_schema_events_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",event_name=~\"$event\"}[$interval])) or sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (irate(mysql_perf_schema_events_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",event_name=~\"$event\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{event_name}}"
    }
   ]
  },
  {
   "title": "Load - Performance Schema Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (rate(mysql_perf_schema_events_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\",event_name=~\"$event\"}[$interval])) or sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (irate(mysql_perf_schema_events_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\",event_name=~\"$event\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{event_name}} "
    }
   ]
  },
  {
   "title": "Avg Wait Time - Performance Schema Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (rate(mysql_perf_schema_events_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\",event_name=~\"$event\"}[$interval])/rate(mysql_perf_schema_events_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\",event_name=~\"$event\"}[$interval])) or sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (irate(mysql_perf_schema_events_waits_seconds_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\",event_name=~\"$event\"}[5m])/irate(mysql_perf_schema_events_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\",event_name=~\"$event\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{event_name}} (wait_seconds_total)"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (rate(mysql_perf_schema_events_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\",event_name=~\"$event\"}[$interval])) or sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,event_name) (irate(mysql_perf_schema_events_waits_total{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$host\",event_name=~\"$event\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{event_name}} (wait_total)"
    }
   ]
  }
 ]
}