{
 "title": "MySQL InnoDB Metrics Overview",
 "description": "MySQL InnoDB metrics overview.",
 "tags": [
  "database",
  "mysql",
  "sgbd"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(mysql_up,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(mysql_up{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(mysql_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "node",
    "label": "Kubernetes Host",
    "query": "label_values(mysql_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_node_name)"
   },
   {
    "name": "host",
    "label": "Pod Name",
    "query": "label_values(mysql_up{kubernetes_cluster=~\"$cluster\",kubernetes_service_name=~\"$deployment\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Checkpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "InnoDB Checkpoint Age",
   "type": "graph",
   "description": "**InnoDB Checkpoint Age**\n\nThe maximum checkpoint age is determined by the total length of all transaction log files (`innodb_log_file_size`).\n\nWhen the checkpoint age reaches the maximum checkpoint age, blocks are flushed syncronously. The rules of the thumb is to keep one hour of traffic in those logs and let the checkpointing perform its work as smooth as possible. If you don't do this, InnoDB will do synchronous flushing at the worst possible time, ie when you are busiest.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (max_over_time(mysql_global_status_innodb_checkpoint_age{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or \nmax_over_time(mysql_global_status_innodb_checkpoint_age{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) or\nmax_over_time(mysql_info_schema_innodb_metrics_recovery_log_lsn_checkpoint_age_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or\nmax_over_time(mysql_info_schema_innodb_metrics_recovery_log_lsn_checkpoint_age_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) or\nmax_over_time(mysql_info_schema_innodb_metrics_log_log_lsn_checkpoint_age{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or\nmax_over_time(mysql_info_schema_innodb_metrics_log_log_lsn_checkpoint_age{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Uncheckpointed Bytes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (max_over_time(mysql_global_status_innodb_checkpoint_max_age{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_innodb_checkpoint_max_age{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) or\nmax_over_time(mysql_info_schema_innodb_metrics_recovery_log_max_modified_age_async{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or\nmax_over_time(mysql_info_schema_innodb_metrics_recovery_log_max_modified_age_async{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) or\nmax_over_time(mysql_info_schema_innodb_metrics_log_log_max_modified_age_async{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or\nmax_over_time(mysql_info_schema_innodb_metrics_log_log_max_modified_age_async{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Max Checkpoint Age"
    }
   ]
  },
  {
   "title": "InnoDB Transactions",
   "type": "graph",
   "description": "**Innodb Transactions** \n\nInnoDB is an MVCC storage engine, which means you can start a transaction and continue to see a consistent snapshot \neven as the data changes. This is implemented by keeping old versions of rows as they are modified.\n\nThe InnoDB History List is the undo logs which are used to store these modifications. They are a fundamental part of InnoDB’s transactional architecture.\n\nIf history length is rising regularly, do not let open connections linger for a long period as this can affect the performance of InnoDB considerably. It is also a good idea to look for long running queries in PMM's Query Analytics.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_max_trx_id{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_max_trx_id{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} InnoDB Transactions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) ((max_over_time(mysql_global_status_innodb_history_list_length{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or \nmax_over_time(mysql_global_status_innodb_history_list_length{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])) or \n(max_over_time(mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or \nmax_over_time(mysql_info_schema_innodb_metrics_transaction_trx_rseg_history_len{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} History Length"
    }
   ]
  },
  { "title": "Row Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "InnoDB Row Operations",
   "type": "graph",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,operation) (rate(mysql_global_status_innodb_row_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Rows {{operation}}"
    }
   ]
  },
  {
   "title": "InnoDB Row Lock Time",
   "type": "graph",
   "description": "**InnoDB Row Lock Time**\n\nWhen data is locked, then that means that another ***session can NOT update that data until the lock*** is released (which unlocks the data and allows other users to update that data). Locks are usually released by either a ROLLBACK or COMMIT SQL statement.\n\nInnoDB implements standard row-level locking where there are two types of locks, [shared (S) locks](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_shared_lock) and [exclusive (X) locks](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_exclusive_lock).\n\n* A [shared (S) lock](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_shared_lock) permits the transaction that holds the lock to read a row.\n* An [exclusive (X) lock](https://dev.mysql.com/doc/refman/5.7/en/glossary.html#glos_exclusive_lock) permits the transaction that holds the lock to update or delete a row.\n\n_Average Row Lock Wait Time_ is the row lock wait time divided by the number of row locks.\\\n_Row Lock Waits_ are how many times a transaction waited on a row lock per second.\\\n_Row Lock Wait Load_ is a rolling 5 minute average of Row Lock Waits.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_row_lock_waits{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval])) or sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (irate(mysql_global_status_innodb_row_lock_waits{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Row Lock Waits"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_row_lock_time{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) / 1000) or sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (irate(mysql_global_status_innodb_row_lock_time{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) / 1000)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Row Lock Wait Load"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_row_lock_time{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) / rate(mysql_global_status_innodb_row_lock_waits{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval])) or sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (irate(mysql_global_status_innodb_row_lock_time{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) / irate(mysql_global_status_innodb_row_lock_waits{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Avg Row Lock Wait Time"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "InnoDB I/O",
   "type": "graph",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_data_reads{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Data Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_data_writes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Data Writes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_data_fsyncs{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_data_fsyncs{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Data Fsyncs"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_log_writes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_log_writes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Log Writes"
    }
   ]
  },
  {
   "title": "InnoDB Log File Usage Hourly",
   "type": "graph",
   "description": "**InnoDB Log File Usage Hourly**\n\nAlong with the buffer pool size, `innodb_log_file_size` is the most important setting when we are working with InnoDB. This graph shows how much data was written to InnoDB's redo logs over each hour. When the InnoDB log files are full, InnoDB needs to flush the modified pages from memory to disk.\n\nThe rules of the thumb is to keep one hour of traffic in those logs and let the checkpointing perform its work as smooth as possible. If you don't do this, InnoDB will do synchronous flushing at the worst possible time, ie when you are busiest.\n\nThis graph can help guide you in setting the correct `innodb_log_file_size`.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (increase(mysql_global_status_innodb_os_log_written{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[1h]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Data Written"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mysql_global_variables_innodb_log_files_in_group{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"} * mysql_global_variables_innodb_log_file_size{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Total Size of InnoDB Log Files"
    }
   ]
  },
  {
   "title": "Innodb Logging Performance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_os_log_written{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_written{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Data Written to Logs"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) ((mysql_global_variables_innodb_log_files_in_group{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"} * mysql_global_variables_innodb_log_file_size{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}) / (rate(mysql_global_status_innodb_os_log_written{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_written{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Time to Use Redo Log Space "
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) ((mysql_global_variables_innodb_log_buffer_size{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}) / (rate(mysql_global_status_innodb_os_log_written{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_os_log_written{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Time to Use In-Memory Log Buffer"
    }
   ]
  },
  { "title": "Deadlocks and ICP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "InnoDB Deadlocks",
   "type": "graph",
   "description": "**InnoDB Deadlocks**\n\nA deadlock in MySQL happens when two or more transactions mutually hold and request for locks, creating a cycle of dependencies. In a transaction system, deadlocks are a fact of life and not completely avoidable. InnoDB automatically detects transaction deadlocks, rollbacks a transaction immediately and returns an error.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) ((rate(mysql_global_status_innodb_deadlocks{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or rate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval])) or (irate(mysql_global_status_innodb_deadlocks{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) or irate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Deadlocks"
    }
   ]
  },
  {
   "title": "Index Condition Pushdown (ICP)",
   "type": "graph",
   "description": "Index Condition Pushdown (ICP) is an optimization for the case where MySQL retrieves rows from a table using an index. Without ICP, the storage engine traverses the index to locate rows in the base table and returns them to the MySQL server which evaluates the WHERE condition for the rows. With ICP enabled, and if parts of the WHERE condition can be evaluated by using only columns from the index, the MySQL server pushes this part of the WHERE condition down to the storage engine. The storage engine then evaluates the pushed index condition by using the index entry and only if this is satisfied is the row read from the table. ICP can reduce the number of times the storage engine must access the base table and the number of times the MySQL server must access the storage engine.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_icp_icp_attempts_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Attempts"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_icp_icp_match_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Matches"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_icp_icp_no_match_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} No Matches"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_info_schema_innodb_metrics_icp_icp_out_of_range_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Out of Range"
    }
   ]
  },
  { "title": "Buffer Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "InnoDB Buffer Pool Content",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mysql_global_status_innodb_buffer_pool_bytes_data{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Data Total"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mysql_global_status_innodb_buffer_pool_bytes_dirty{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Data Dirty"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name,state) (mysql_global_status_buffer_pool_pages{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\",state=~\"free|data|misc\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} {{state}}"
    }
   ]
  },
  { "title": "Buffer Pool I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "InnoDB Buffer Pool I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_pages_created{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_created{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Pages Created"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_pages_read{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_read{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Pages Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_pages_written{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_written{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Pages Written"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_buffer_pool_read_requests{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Read Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_buffer_pool_write_requests{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Write Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_buffer_pool_reads{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_reads{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Disk Reads"
    }
   ]
  },
  {
   "title": "Innodb Read-Ahead",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_buffer_pool_read_ahead{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Pages Fetched by Linear Read Ahead "
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Paged Fetched by Random Read Ahead"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Paged Fetched by Read Ahead but Never Accessed"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) ((rate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])) / ((rate(mysql_global_status_innodb_buffer_pool_read_ahead{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])) + (rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Read Ahead Waste Percent"
    },
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (((rate(mysql_global_status_innodb_buffer_pool_read_ahead{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))+(rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])))/(rate(mysql_global_status_innodb_pages_read{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_pages_read{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m])))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Percent of IO Caused by Read Ahead"
    }
   ]
  },
  { "title": "Change/Insert Buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "InnoDB Change Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (mysql_global_status_innodb_ibuf_segment_size{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"} * mysql_global_status_innodb_page_size{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Allocated"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) ((mysql_global_status_innodb_ibuf_segment_size{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"} - mysql_global_status_innodb_ibuf_free_list{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}) * mysql_global_status_innodb_page_size{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Used"
    }
   ]
  },
  {
   "title": "InnoDB Change Buffer Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_ibuf_merges{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merges{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Merges"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_ibuf_merged_inserts{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_inserts{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_insert_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Merged Inserts"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_ibuf_merged_deletes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_deletes{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Merged Deletes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_pod_name) (rate(mysql_global_status_innodb_ibuf_merged_delete_marks{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_global_status_innodb_ibuf_merged_delete_marks{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]) or rate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_change_buffer_ibuf_merges_delete_mark_total{kubernetes_cluster=~\"$cluster\",kubernetes_node_name=~\"$node\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$host\"}[5m]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_pod_name}} Merged Delete Marks"
    }
   ]
  }
 ]
}