{
 "title": "MySQL Table Statistics",
 "description": "MySQL Table Stats overview.",
 "tags": [
  "database",
  "mysql",
  "sgbd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(mysql_up,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(mysql_up{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "host",
    "label": "Kubernetes Service  Name",
    "query": "label_values(mysql_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   }
  ]
 },
 "panels": [
  { "title": "Largest Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Largest Tables by Row Count",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(10,sum(mysql_info_schema_table_rows{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,schema,table)) > 0",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{schema}}.{{table}}"
    }
   ]
  },
  {
   "title": "Largest Tables by Size",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(10,sum(mysql_info_schema_table_size{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\",component!=\"data_free\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,schema,table)) > 0",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}/{{schema}}.{{table}}"
    }
   ]
  },
  { "title": "Pie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Database Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (mysql_info_schema_table_size{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\",component!=\"data_free\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Data + Index Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (mysql_info_schema_table_size{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\",component=\"data_free\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} Freeable Size"
    }
   ]
  },
  {
   "title": "Most Fragmented Tables by Freeable Size",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(5,sum(mysql_info_schema_table_size{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\",component=\"data_free\"}) by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,schema,table))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{schema}}.{{table}}"
    }
   ]
  },
  { "title": "Auto Increment Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Top Tables by Auto Increment Usage",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(10,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,schema,table) (mysql_info_schema_auto_increment_column{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\"} / mysql_info_schema_auto_increment_column_max{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\"}))"
    }
   ]
  },
  { "title": "Rows read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Top Tables by Rows Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,schema,table) (rate(mysql_info_schema_table_statistics_rows_read_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\"}[$interval]) > 0)) or topk(5,sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name,schema,table) (irate(mysql_info_schema_table_statistics_rows_read_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{schema}}.{{table}}"
    }
   ]
  },
  { "title": "Rows Changed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Top Tables by Rows Changed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk(5,sum by (kuberetes_cluster,kubernetes_namespace,kubernetes_service_name,schema,table) (rate(mysql_info_schema_table_statistics_rows_changed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\"}[$interval]) > 0)) or topk(5,sum by (kuberetes_cluster,kubernetes_namespace,kubernetes_service_name,schema,table) (irate(mysql_info_schema_table_statistics_rows_changed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$host\"}[5m]) > 0))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{schema}}.{{table}}"
    }
   ]
  }
 ]
}