{
 "title": "Prometheus",
 "description": "Prometheus metrics overview.",
 "tags": [
  "application",
  "go",
  "monitoring",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(prometheus_tsdb_head_samples_appended_total,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(prometheus_tsdb_head_samples_appended_total{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "job",
    "query": "label_values(prometheus_tsdb_head_samples_appended_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},job)"
   },
   {
    "name": "instance",
    "label": "Kubernetes Deployment",
    "query": "label_values(prometheus_tsdb_head_samples_appended_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",job=~\"$job\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "at a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime [$interval]",
   "type": "singlestat",
   "description": "Percentage of uptime during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(avg_over_time(up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Currently Down",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"} < 1"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "singlestat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  { "title": "quick numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Missed Iterations [$interval]",
   "type": "singlestat",
   "description": "The total number of rule group evaluations missed due to slow rule group evaluation.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_evaluator_iterations_missed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Skipped Iterations [$interval]",
   "type": "singlestat",
   "description": "The total number of rule group evaluations skipped due to throttled metric storage.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_evaluator_iterations_skipped_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tardy Scrapes [$interval]",
   "type": "singlestat",
   "description": "Total number of scrapes that hit the sample limit and were rejected.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Reload Failures [$interval]",
   "type": "singlestat",
   "description": "Number of times the database failed to reload block data from disk.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_tsdb_reloads_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Skipped Scrapes [$interval]",
   "type": "singlestat",
   "description": "Sum of all skipped scrapes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_duplicate_timestamp_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_bounds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_order_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval])) "
    }
   ]
  },
  { "title": "errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Failures and Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Failed Connections"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_missed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Missed Iterations"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_skipped_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Skipped Iterations"
    },
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Evaluation"
    },
    {
     "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Azure Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Consul RPC"
    },
    {
     "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "DNS Lookup"
    },
    {
     "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "EC2 Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "GCE Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Marathon Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Openstack Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Triton Refresh"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Sample Limit"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Duplicate Timestamp"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Timestamp Out of Bounds"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Sample Out of Order"
    },
    {
     "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "TSDB Compactions"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_not_found{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Series Not Found"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval])) > 0",
     "legendFormat": "Reload"
    }
   ]
  },
  { "title": "up", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Upness (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "Up" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Storage Memory Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Chunks" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (prometheus_tsdb_head_chunks{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  { "title": "series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Series Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Series" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (prometheus_tsdb_head_series{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Series Created / Removed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Series Count" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_created_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval]))",
     "legendFormat": "created"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_removed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval]))",
     "legendFormat": "removed"
    }
   ]
  },
  { "title": "appended samples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Appended Samples per Second",
   "type": "graph",
   "description": "Rate of total number of appended samples",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Samples / Second" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (rate(prometheus_tsdb_head_samples_appended_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  { "title": "sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Scrape Sync Total",
   "type": "graph",
   "description": "Total number of syncs that were executed on a scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Syncs" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_sync_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}) by (scrape_job)",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Target Sync",
   "type": "graph",
   "description": "Actual interval to sync the scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval])) by (scrape_job) * 1000",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  { "title": "scrapes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Rejected Scrapes",
   "type": "graph",
   "description": "Total number of rejected scrapes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Scrapes" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "exceeded sample limit"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "duplicate timestamp"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "out of bounds"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}) ",
     "legendFormat": "out of order"
    }
   ]
  },
  { "title": "durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Average Rule Evaluation Duration",
   "type": "graph",
   "description": "The duration of rule group evaluations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (1000 * rate(prometheus_rule_evaluation_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]) / rate(prometheus_rule_evaluation_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "ms", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_request_duration_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval])) by (handler) > 0",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Prometheus Engine Query Duration Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_engine_query_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}) by (slice)",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Rule Evaluator Iterations",
   "type": "graph",
   "description": "Rule-group evaluations \n - total\n - missed due to slow rule group evaluation\n - skipped due to throttled metric storage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "iterations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_rule_group_iterations_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(prometheus_rule_group_iterations_missed_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "Missed"
    },
    {
     "expr": "sum(rate(prometheus_evaluator_iterations_skipped_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval]))",
     "legendFormat": "Skipped"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum by (quantile,interval,kubernetes_namespace,kubernetes_cluster,kubernetes_service_name) (prometheus_target_interval_length_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}} {{quantile}} {{interval}}"
    }
   ]
  },
  {
   "title": "Target Scrapes / $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "Scrapes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_interval_length_seconds_count{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval])) by (interval)",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  { "title": "notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Notifications Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short", "label": "Notifications" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (rate(prometheus_notifications_sent_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\"}[$interval]))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  { "title": "config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Time Since Successful Config Reload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) ((time() - prometheus_config_last_reload_success_timestamp_seconds{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}))",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  {
   "title": "Successful Config Reload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short", "label": "Success" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_cluster,kubernetes_namespace,kubernetes_service_name) (prometheus_config_last_reload_successful{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  },
  { "title": "garbage collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "GC Rate / $interval",
   "type": "graph",
   "description": "GC invocation durations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$instance\",job=~\"$job\"}[$interval])) by (kubernetes_namespace,kubernetes_cluster,kubernetes_service_name)",
     "legendFormat": "{{kubernetes_namespace}}/{{kubernetes_service_name}}"
    }
   ]
  }
 ]
}