{
 "title": "Squid",
 "description": "Squid overview.",
 "tags": [
  "squid",
  "proxy"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,5m,10m,1h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(squid_up,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(squid_up{kubernetes_cluster=~\"$cluster\"},kubernetes_namespace)"
   },
   {
    "name": "deployment",
    "label": "Kubernetes Deployment",
    "query": "label_values(squid_client_http_hits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\"},kubernetes_service_name)"
   },
   {
    "name": "podname",
    "label": "Pod Name",
    "query": "label_values(squid_client_http_hits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Proxies",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(squid_up{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})"
    }
   ]
  },
  {
   "title": "Bytes Hit Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(squid_client_http_hit_kbytes_out_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}) / sum(squid_client_http_kbytes_out_kbytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})"
    }
   ]
  },
  {
   "title": "Bytes Hit Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(squid_client_http_hit_kbytes_out_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}) / sum(squid_client_http_kbytes_out_kbytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(squid_client_http_errors_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}) / sum(squid_client_http_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"})"
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(squid_client_http_requests_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "Total Requests {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(squid_client_http_hits_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "Total HTTP hits {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(squid_client_http_errors_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "Total Errors {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(squid_client_http_kbytes_in_kbytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval]) * -1",
     "legendFormat": "HTTP Traffic in {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(squid_client_http_kbytes_out_kbytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "HTTP Traffic Out {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(squid_client_http_hit_kbytes_out_bytes_total{kubernetes_cluster=~\"$cluster\",kubernetes_namespace=~\"$namespace\",kubernetes_service_name=~\"$deployment\",kubernetes_pod_name=~\"$podname\"}[$interval])",
     "legendFormat": "HTTP Traffic Out Hits {{kubernetes_namespace}}/{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}