{
 "title": "Tekton PipelineRuns",
 "description": "Tekton Pipelines - PipelineRuns metrics overview.",
 "tags": [
  "kubernetes",
  "pipelines",
  "tekton"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kubernetes Cluster",
    "query": "label_values(tekton_pipelinerun_duration_seconds_sum,kubernetes_cluster)"
   },
   {
    "name": "namespace",
    "label": "Kubernetes Namespace",
    "query": "label_values(tekton_pipelinerun_duration_seconds_sum{kubernetes_cluster=~\"$cluster\"},namespace)"
   },
   {
    "name": "pipeline",
    "label": "Tekton Pipeline",
    "query": "label_values(tekton_pipelinerun_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\"},pipeline)"
   },
   {
    "name": "pipelinerun",
    "label": "Tekton PipelineRun",
    "query": "label_values(tekton_pipelinerun_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pipeline=~\"$pipeline\"},pipelinerun)"
   }
  ]
 },
 "panels": [
  {
   "title": "Currently Running Pipelines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tekton_running_pipelineruns_count{kubernetes_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Top 15 PipelineRuns Runtime",
   "type": "stat",
   "gridPos": { "h": 20, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(15, sum by (kubernetes_cluster,namespace,pipeline,pipelinerun) (tekton_pipelinerun_duration_seconds_sum{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pipeline=~\"$pipeline\",pipelinerun=~\"$pipelinerun\"} / tekton_pipelinerun_duration_seconds_count{kubernetes_cluster=~\"$cluster\",namespace=~\"$namespace\",pipeline=~\"$pipeline\",pipelinerun=~\"$pipelinerun\"}))",
     "legendFormat": "{{namespace}}/{{pipelinerun}}"
    }
   ]
  },
  {
   "title": "Successfull Builds Ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum(tekton_pipelinerun_count{kubernetes_cluster=~\"$cluster\",status=~\"success\"}) / sum(tekton_pipelinerun_count{kubernetes_cluster=~\"$cluster\",status=~\".+\"})"
    }
   ]
  },
  {
   "title": "Total Pipeline Runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(tekton_pipelinerun_count{kubernetes_cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Failed Builds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tekton_pipelinerun_count{kubernetes_cluster=~\"$cluster\",status=\"failed\"}"
    }
   ]
  }
 ]
}