apiVersion: v1
kind: ConfigMap
metadata:
  name: config-traefik
  namespace: traefik
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
           [[entryPoints.https.tls.certificates]]
           CertFile = "/data/tls/tls.crt"
           KeyFile = "/data/tls/tls.key"
    [accessLog]
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]
