---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: traefik-ingress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress
    spec:
      containers:
      - args:
        - --kubernetes
        - --configfile=/data/config/traefik.toml
        - --logLevel=INFO
        image: traefik:v1.7
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8080
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /data/tls
          name: certs
        - mountPath: /data/config
          name: config
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/infra: "true"
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: certs
        secret:
          secretName: traefik-tls
      - configMap:
          name: config-traefik
        name: config
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress
  namespace: traefik
spec:
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: admin
      port: 8080
  selector:
    k8s-app: traefik-ingress
