- include_role:
    name: commons
    tasks_from: helpers/namespace.yaml
  vars:
    k8s_api_node: "{{ inventory_hostname }}"
    kube_client: oc
    ns_name: "{{ projname | default('default') }}"

- name: Checks for Ceph Secret
  failed_when: False
  changed_when: False
  register: ceph_secret_check
  shell: "oc describe secret -n {{ projname | default('default') }} ceph-secret-{{ kuser }}"
- block:
  - name: Prepares Ceph Secret
    template:
      dest: "/tmp/ceph-secret-{{ kuser }}.yml"
      group: root
      mode: 0600
      owner: root
      src: ceph-secret.j2
  - name: Installs Ceph Secret
    args:
      chdir: /tmp
    shell: |
        oc create -n "{{ projname | default('default') }}" -f "ceph-secret-{{ kuser }}.yml" \
          && rm -f "ceph-secret-{{ kuser }}.yml"
  when:
  - ceph_secret_check is defined
  - (ceph_secret_check.rc | default(0)) != 0
