apiVersion: v1
data:
  config.json: |-
    [
      {
        "clusterID": "7f3dc6eb-a523-4339-b119-401363946932",
        "monitors": [
          "10.42.253.110",
          "10.42.253.111",
          "10.42.253.112"
        ],
        "cephFS": {
          "subvolumeGroup": "k8scsi"
        }
      }
    ]
kind: ConfigMap
metadata:
  name: ceph-csi-config
  namespace: rbd-provisioner
