---
ansible_user: root
# bullseye
ansible_python_interpreter: /usr/bin/python3

ceph_origin: repository
ceph_repository: community
#ceph_repository_type: cdn
ceph_stable_release: quincy

monitor_interface: ens3
public_network: "10.42.253.0/24"
cluster_network: "10.42.253.0/24"

dashboard_enabled: false
configure_firewall: false
containerized_deployment: False


osd_objectstore: bluestore
# 2Gi (defaults: 4)
osd_memory_target: 2147483648
# 128Mi (defaults: ? / did not check)
ceph_tcmalloc_max_total_thread_cache: 134217728
