---
# containerd_storage_dir: "/var/lib/containerd"
# containerd_state_dir: "/run/containerd"
# containerd_oom_score: 0

# containerd_default_runtime: "runc"
# containerd_snapshotter: "native"

# containerd_runtimes:
#   - name: runc
#     type: "io.containerd.runc.v2"
#     engine: ""
#     root: ""
# Example for Kata Containers as additional runtime:
#   - name: kata
#     type: "io.containerd.kata.v2"
#     engine: ""
#     root: ""

# containerd_grpc_max_recv_message_size: 16777216
# containerd_grpc_max_send_message_size: 16777216

# containerd_debug_level: "info"

# containerd_metrics_address: ""

# containerd_metrics_grpc_histogram: false

containerd_registries:
  "docker.io": "https://registry-1.docker.io"
  katello: "https://katello.vms.intra.unetresgrossebite.com:5000"
  "registry.registry.svc.cluster.local:5000": "http://registry.registry.svc.cluster.local:5000"
  "registry-kube.default.svc.cluster.local:5000": "http://registry-kube.default.svc.cluster.local:5000"

# containerd_max_container_log_line_size: -1

# fix:
# roles/kubernetes/control-plane/tasks/psp-install.yml
# roles/kubernetes-apps/metallb/tasks/main.yml
# roles/kubernetes-apps/ansible/tasks/netchecker.yml
# - name: Kubernetes Apps | Check AppArmor status
#   #command: which apparmor_parser
#   command: grep Y /sys/module/apparmor/parameters/enabled
#     ^-- change command with that one, that actually confirms we may use apparmor
#         ... which, in my raspbians, is not the case/don't want to change my kernel options 2years after deploying that cluster...
#   register: apparmor_status
#   when:
#     - podsecuritypolicy_enabled
#     - inventory_hostname == groups['kube_control_plane'][0]
#   failed_when: false
