---
# containerd_storage_dir: "/var/lib/containerd"
# containerd_state_dir: "/run/containerd"
# containerd_oom_score: 0

# containerd_default_runtime: "runc"
# containerd_snapshotter: "native"

# containerd_runtimes:
#   - name: runc
#     type: "io.containerd.runc.v2"
#     engine: ""
#     root: ""
# Example for Kata Containers as additional runtime:
#   - name: kata
#     type: "io.containerd.kata.v2"
#     engine: ""
#     root: ""

# containerd_grpc_max_recv_message_size: 16777216
# containerd_grpc_max_send_message_size: 16777216

# containerd_debug_level: "info"

# containerd_metrics_address: ""

# containerd_metrics_grpc_histogram: false

containerd_registries:
  "docker.io": "https://registry-1.docker.io"
  katello: "https://katello.vms.intra.unetresgrossebite.com:5000"
  "registry.registry.svc.cluster.local:5000": "http://registry.registry.svc.cluster.local:5000"
  "registry-kube.default.svc.cluster.local:5000": "http://registry-kube.default.svc.cluster.local:5000"

# containerd_max_container_log_line_size: -1

# fix roles/kubernetes-apps/cluster_roles/tasks/main.yml
# - name: Kubernetes Apps | Check AppArmor status
#   #command: which apparmor_parser
#   command: grep Y /sys/module/apparmor/parameters/enabled
#     ^-- change command with that one, that actually confirms we may use apparmor
#         ... which, in my raspbians, is not the case/don't want to change my kernel options 2years after deploying that cluster...
#   register: apparmor_status
#   when:
#     - podsecuritypolicy_enabled
#     - inventory_hostname == groups['kube_control_plane'][0]
#   failed_when: false

# missing arm64 binaries running kubespray v2.18.2 / kubernetes 1.22.8!
# see https://github.com/kubernetes-sigs/kubespray/issues/8384
containerd_version: 1.6.0-beta.5
runc_version: v1.1.0-rc.1

# runc_checksums:
#   arm:
#     v1.0.2: 0
#     v1.0.3: 0
#   arm64:
#     v1.0.2: 0
#     v1.0.3: edda26f24f9137f5e6981583dc0e782ea9e3ffee591d4c7a9f9565adc2ed9461
#     v1.1.0-rc.1: 6d5225976b51724ea0e693e34af74890f59d60e45cf76608e9562ab9347f1f31
#       ^-- add this!
#   amd64:
#     v1.0.2: 44d1ba01a286aaf0b31b4be9c6abc20deab0653d44ecb0d93b4d0d20eac3e0b6
#     v1.0.3: 5d4c0e5a4e8d6ccbb9c6696bb239f31cfab8d94b15801bafe09aaee600714f61
# containerd_archive_checksums:
#   arm:
#     1.4.9: 0
#     1.4.11: 0
#     1.4.12: 0
#     1.5.5: 0
#     1.5.7: 0
#     1.5.8: 0
#   arm64:
#     1.4.9: 0
#     1.4.11: 0
#     1.4.12: 0
#     1.5.5: 0
#     1.5.7: 0
#     1.5.8: 0
#     1.6.0-beta.5: d4285d78aa156eb2f70830faf725450417bb9dde229525efc8c3e43131543853
#       ^-- add this!
#   amd64:
#     1.4.9: 346f88ad5b973960ff81b5539d4177af5941ec2e4703b479ca9a6081ff1d023b
#     1.4.11: 80c47ec5ce2cd91a15204b5f5b534892ca653e75f3fba0c451ca326bca45fb00
#     1.4.12: 26bb35ee8a2467029ca450352112ba3a0d2b8bf6b70bf040f62d91f3c501736c
#     1.5.5: 8efc527ffb772a82021800f0151374a3113ed2439922497ff08f2596a70f10f1
#     1.5.7: 109fc95b86382065ea668005c376360ddcd8c4ec413e7abe220ae9f461e0e173
#     1.5.8: feeda3f563edf0294e33b6c4b89bd7dbe0ee182ca61a2f9b8c3de2766bcbc99b
