---
containerd_config:
  grpc:
    max_recv_message_size: 16777216
    max_send_message_size: 16777216
  debug:
    level: ""
  registries:
    docker.io: "https://registry-1.docker.io"
    katello: "https://katello.vms.intra.unetresgrossebite.com:5000"
  max_container_log_line_size: -1
  metrics:
    address: ""
    grpc_histogram: false
