- hosts: mons[0]
  roles:
  - post-deploy-ceph

- hosts: masters[0]
  roles:
  - ldapgroupsync
  - post-deploy-openshift

- hosts: k8s-cluster:lbs:etcd:mon:OSEv3
  roles:
  - nagios

- hosts: k8s-cluster:OSEv3
  roles:
  - post-deploy-host
