- hosts: kube-master[0]
  vars:
    admin_kubeconfig: "{{ custom_admin_kubeconfig | default('/etc/kubernetes/admin.conf') }}"
    kube_client: kubectl
    prometheus_ns: prometheus-monitoring
  roles:
  - prometheus
- hosts: OSEv3[0]
  vars:
    admin_kubeconfig: "{{ custom_admin_kubeconfig | default('/etc/origin/master/admin.kubeconfig') }}"
    kube_client: oc
    prometheus_ns: prometheus-monitoring
  roles:
  - prometheus
