- name: Generates AlertManager Configuration
  template:
    dest: /tmp/alertmanager.yaml
    group: root
    mode: 0640
    owner: root
    src: alertmanager.j2
- name: Installs AlertManager
  args:
    chdir: /tmp
  shell: |
    oc --config {{ admin_kubeconfig }} apply -f alertmanager.yaml
- name: Cleanups AlertManager Temporary Assets
  file:
    dest: /tmp/alertmanager.yaml
    state: absent
