- include_tasks: install-grafana-dashboard.yaml
  vars:
    dashboard_name: "{{ item }}"
  with_items: "{{ grafana_dashboards }}"
- name: Generates Grafana Configuration
  vars:
    grafana_upstream: "http://{{ ('prometheus.' ~ prometheus_ns ~ '.svc.' ~ cluster_domain)
                                   if (not (do_thanos | default(False)))
                                   else (('thanos-queryfrontend.' ~ prometheus_ns ~ '.svc.' ~ cluster_domain)
                                        if (do_thanos_queryfrontend | default(False))
                                        else ('thanos-query.' ~ prometheus_ns ~ '.svc.' ~ cluster_domain))
                              }}:9090"
  template:
    dest: /tmp/grafana.yaml
    group: root
    mode: 0640
    owner: root
    src: grafana.j2
- name: Installs Grafana
  args:
    chdir: /tmp
  shell: |
    oc --config {{ admin_kubeconfig }} apply -f grafana.yaml
- name: Cleanups Grafana Temporary Assets
  file:
    dest: /tmp/grafana.yaml
    state: absent
