- name: Checks for Existing Grafana Ingress
  changed_when: False
  failed_when: False
  register: has_ig
  shell: "{{ kube_client }} --kubeconfig {{ admin_kubeconfig }} -n {{ logging_ns }} describe ingress grafana"
- block:
  - block:
    - name: Set TLS Provier Facts
      set_fact:
        sc_name: grafana-tls
        sc_namespace: "{{ prometheus_ns }}"
        sc_cn: "{{ grafana_fqdn }}"
        sc_org: UTGB
## FIXME / cert-manager ##
        tls_provider: "{{ 'certmgr' if ((cert_manager_enable | default(False))
                                        and 0 == 1)
                                    else 'self-signed' }}"
## FIXME / cert-manager ##
    - include_role:
        name: commons
        tasks_from: "ssl/{{ tls_provider }}.yaml"
    when:
    - grafana_do_tls | default(True)
  - block:
    - name: Set TLS Provier Facts
      set_fact:
        sc_name: alertmanager-tls
        sc_namespace: "{{ prometheus_ns }}"
        sc_cn: "{{ alertmanager_fqdn }}"
        sc_org: UTGB
## FIXME / cert-manager ##
        tls_provider: "{{ 'certmgr' if ((cert_manager_enable | default(False))
                                        and 0 == 1)
                                    else 'self-signed' }}"
## FIXME / cert-manager ##
    - include_role:
        name: commons
        tasks_from: "ssl/{{ tls_provider }}.yaml"
    when:
    - alertmanager_do_tls | default(True)
  - block:
    - name: Set TLS Provier Facts
      set_fact:
        sc_name: prometheus-tls
        sc_namespace: "{{ prometheus_ns }}"
        sc_cn: "{{ prometheus_fqdn }}"
        sc_org: UTGB
## FIXME / cert-manager ##
        tls_provider: "{{ 'certmgr' if ((cert_manager_enable | default(False))
                                        and 0 == 1)
                                    else 'self-signed' }}"
## FIXME / cert-manager ##
    - include_role:
        name: commons
        tasks_from: "ssl/{{ tls_provider }}.yaml"
    when:
    - prometheus_do_tls | default(True)
  - name: Generates Prometheus Ingress Configuration
    template:
      dest: /tmp/ig.yaml
      group: root
      mode: 0640
      owner: root
      src: ingress.j2
  - name: Installs Prometheus Ingress
    args:
      chdir: /tmp
    shell: "{{ kube_client }} --kubeconfig {{ admin_kubeconfig }} apply -f ig.yaml"
  - name: Cleanups Prometheus Ingress Temporary Assets
    file:
      dest: /tmp/ig.yaml
      state: absent
  when:
  - has_ig is defined
  - (has_ig.rc | default(0)) != 0
