- name: "Generates Prometheus Rules {{ rule_file }} Configuration"
  template:
    dest: /tmp/rule.yaml
    group: root
    mode: 0640
    owner: root
    src: rule.j2
- name: "Installs Prometheus Rules {{ rule_file }}"
  args:
    chdir: /tmp
  shell: |
    oc --config {{ admin_kubeconfig }} apply -f rule.yaml
- name: Cleanups Prometheus Rules Temporary Assets
  file:
    dest: /tmp/rule.yaml
    state: absent
