- name: Generates Node-Exporter Configuration
  template:
    dest: /tmp/node-exporter.yaml
    group: root
    mode: 0640
    owner: root
    src: node-exporter.j2
- name: Installs Node-Exporter
  args:
    chdir: /tmp
  shell: |
    oc --config {{ admin_kubeconfig }} apply -f node-exporter.yaml
- name: Cleanups Node-Exporter Temporary Assets
  file:
    dest: /tmp/node-exporter.yaml
    state: absent
