- include_tasks: install-prometheus-rules.yaml
  vars:
    rule_file: "{{ item }}"
  with_items: "{{ prometheus_rules }}"
- name: Generates Prometheus Configuration
  template:
    dest: /tmp/prometheus.yaml
    group: root
    mode: 0640
    owner: root
    src: prometheus.j2
- name: Installs Prometheus
  args:
    chdir: /tmp
  shell: |
    oc --config {{ admin_kubeconfig }} apply -f prometheus.yaml
- name: Cleanups Prometheus Temporary Assets
  file:
    dest: /tmp/prometheus.yaml
    state: absent
