- name: Generates Prometheus RBAC Configuration
  template:
    dest: /tmp/prometheus-rbac.yaml
    group: root
    mode: 0640
    owner: root
    src: rbac.j2
- name: Installs Prometheus RBAC
  args:
    chdir: /tmp
  shell: |
    oc --config {{ admin_kubeconfig }} apply -f prometheus-rbac.yaml
- name: Cleanups Prometheus RBAC Temporary Assets
  file:
    dest: /tmp/prometheus-rbac.yaml
    state: absent

