---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress
  namespace: traefik
spec:
  replicas: 3
  selector:
    matchLabels:
      name: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: traefik
    spec:
      containers:
      - args:
        - --configfile=/data/config/traefik.toml
        image: traefik:v2.3
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8100
        - containerPort: 9113
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: true
        volumeMounts:
        - mountPath: /data/config/traefik.toml
          name: config
          subPath: traefik.toml
        - mountPath: /data/tls
          name: certs
        - mountPath: /data/static/dash.toml
          name: config
          subPath: dash.toml
        - mountPath: /data/static/tls.toml
          name: config
          subPath: tls.toml
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/infra: "true"
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: certs
        secret:
          secretName: traefik-tls
      - configMap:
          name: traefik
        name: config
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress
  namespace: traefik
spec:
  ports:
  - name: web
    port: 80
  - name: websecure
    port: 443
  selector:
    name: traefik
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: scrape-me
  name: exporter-traefik
  namespace: traefik
spec:
  ports:
  - name: exporter-9113
    port: 9113
  selector:
    name: traefik
  type: ClusterIP
