---
dashboard_enabled: true
helm_enabled: false

# Registry deployment
registry_enabled: false
registry_namespace: registry
registry_storage_class: rwx-storage
registry_disk_size: 500Gi

metrics_server_enabled: true
metrics_server_resizer: false
metrics_server_kubelet_insecure_tls: true
metrics_server_metric_resolution: 60s
metrics_server_kubelet_preferred_address_types: InternalIP

cephfs_provisioner_enabled: false
#cephfs_provisioner_enabled: true
cephfs_provisioner_namespace: cephfs-provisioner
cephfs_provisioner_cluster: ceph
#cephfs_provisioner_monitors: "10.42.253.110:6789,10.42.253.111:6789,10.42.253.112:6789"
cephfs_provisioner_admin_id: admin
#cephfs_provisioner_secret: xx
cephfs_provisioner_storage_class: rwx-storage
cephfs_provisioner_reclaim_policy: Delete
cephfs_provisioner_claim_root: /volumes
cephfs_provisioner_deterministic_names: true

rbd_provisioner_enabled: false
#rbd_provisioner_enabled: true
rbd_provisioner_namespace: rbd-provisioner
rbd_provisioner_replicas: 2
#rbd_provisioner_monitors: "10.42.253.110:6789,10.42.253.111:6789,10.42.253.112:6789"
rbd_provisioner_pool: kube
rbd_provisioner_admin_id: admin
rbd_provisioner_secret_name: ceph-secret-admin
#rbd_provisioner_secret: xx
rbd_provisioner_user_id: kube
rbd_provisioner_user_secret_name: ceph-secret-user
#rbd_provisioner_user_secret: xx
rbd_provisioner_user_secret_namespace: "{{ rbd_provisioner_namespace }}"
rbd_provisioner_fs_type: ext4
rbd_provisioner_image_format: "2"
rbd_provisioner_image_features: layering
rbd_provisioner_storage_class: rwo-storage
rbd_provisioner_reclaim_policy: Delete

ingress_ambassador_enabled: false

ingress_nginx_enabled: false
#ingress_nginx_enabled: true
ingress_nginx_host_network: true
ingress_publish_status_address: ""
ingress_nginx_nodeselector:
  node-role.kubernetes.io/infra: "true"
ingress_nginx_namespace: ingress-nginx
ingress_nginx_insecure_port: 80
ingress_nginx_secure_port: 443
ingress_nginx_configmap:
  map-hash-bucket-size: "512"
ingress_nginx_class: nginx

cert_manager_enabled: false
#cert_manager_enabled: true
cert_manager_namespace: cert-manager

metallb_enabled: false

krew_enabled: false
krew_root_dir: "/usr/local/krew"

argocd_enabled: false
